server:
  port: ${PORT:8080}

router:
  secret: ${ROUTER_SECRET:MY_SECRET_123}

telegram:
  botToken: ${TELEGRAM_BOT_TOKEN:PASTE_TOKEN_HERE}

spring:
  sql:
    init:
      mode: always
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}